# Permalinks
permalink:           pretty

# Setup
title:               vbalnt-blog
tagline:             ''
#url:                 http://vbalnt.github.io/
description:         'Random notes.'
paginate:            7
markdown: kramdown
highlighter:         rouge
baseurl: ""
  
# About/contact
author:
  name:              'vbalnt'
  email:             'v.balntas@imperial.ac.uk'
  url:               'http://www.iis.ee.ic.ac.uk/~vbalnt/'
  github:            'https://github.com/vbalnt'
  twitter:           'https://twitter.com/vbalnt'

# Custom vars
version:             1.0

github:
  repo:              https://github.com/vbalnt/vbalnt.github.io

excerpt_separator:   <!--more-->

gems: [jekyll-paginate]

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - output
  - Gruntfile.js
  - package.json
  - tasks.py
  - node_modules
  - dist
